### ISSUE TITLE
Inefficient and Incorrect Generated Code for CHOICEs

### ISSUE THREAD

**Issue by usr3-1415** [maxime-esa/asn1scc#307]
The code generated for the `_IsConstraintValid` function currently checks all union discriminators instead of just the relevant one. Additionally, the generated `isValid` function has a flaw in handling error cases, leading to potential incorrect validation results.

**Problem:**

The generated `isValid` function for `LARGE_CHOICE_IsConstraintValid` looks as follows:

```c
flag SMALL_CHOICE_IsConstraintValid(const SMALL_CHOICE* pVal, int* pErrCode)
{
  flag ret = TRUE;
  if (pVal->kind == bool8Type_PRESENT) {
    ret = PUSC_BOOL8_IsConstraintValid((&(pVal->u.bool8Type)), pErrCode);
  }
  if (ret) {
    if (pVal->kind == float32Type_PRESENT) {
      ret = PUSC_FLOAT32_IsConstraintValid((&(pVal->u.float32Type)), pErrCode);
    }
  }   /*COVERAGE_IGNORE*/

  return ret;
}
```

This code has two major issues:

1. **Inefficient Validation Checks:**
   - The function checks all union discriminators sequentially, rather than stopping once the relevant discriminator is validated. This results in unnecessary checks and potential performance issues for large choice types.

2. **Missing Error Handling:**
   - If `pVal->kind` has an invalid value that does not match any valid discriminator, the function defaults to returning `TRUE`. This is incorrect because the function should return `FALSE` or handle the error appropriately if an invalid discriminator is encountered.

**Proposed Solution:**

1. **Optimize the Validation Logic:**
   - Modify the function to check only the relevant union discriminator and return the result immediately once a match is found.

2. **Implement Proper Error Handling:**
   - Ensure that the function correctly handles cases where `pVal->kind` has an invalid value, returning `FALSE` or setting an appropriate error code.

**Example of Desired Behavior:**

```c
flag SMALL_CHOICE_IsConstraintValid(const SMALL_CHOICE* pVal, int* pErrCode)
{
  flag ret = TRUE;
  switch (pVal->kind) {
    case bool8Type_PRESENT:
      ret = PUSC_BOOL8_IsConstraintValid((&(pVal->u.bool8Type)), pErrCode);
    case float32Type_PRESENT:
      ret = PUSC_FLOAT32_IsConstraintValid((&(pVal->u.float32Type)), pErrCode);
    default:
      *pErrCode = INVALID_KIND_ERROR;
      ret= FALSE;
  }
  return ret;
}
```

This solution ensures that the function performs only the necessary checks and correctly handles invalid discriminator values.

**Comment by maxime-esa** [comment]
fixed in release https://github.com/maxime-esa/asn1scc/releases/tag/4.5.2.1
