### ISSUE TITLE
BOOLEAN ACN Encoding Issue

### ISSUE THREAD

**Issue by usr3-1415** [maxime-esa/asn1scc#309]
The current ACN encoding for BOOLEAN types in version 4.2.4.6f allows users to specify only `true-value` or `false-value`, but only the `false-value` is being considered, and the `true-value` is ignored without any warning. This behavior can lead to incorrect assumptions and potentially faulty encoding/decoding processes.

### Steps to Reproduce

1. Define a BOOLEAN type in ASN.1:
   ```asn
   Boolean8 ::= BOOLEAN
   ```
2. Specify the ACN encoding:
   ```acn
   Boolean8 [false-value '00000000'B, true-value '00000001'B]
   ```
3. Generate code using asn1scc.
4. Observe that the generated encoder and decoder do not correctly handle the `false-value`.

### Expected Behavior

1. Users should be able to specify both `true-value` and `false-value`.
2. The decoder should check for both patterns. If the pattern does not match either `true-value` or `false-value`, it should raise a decoding error instead of silently converting to `false`.

#### ASN.1
```asn
Boolean8 ::= BOOLEAN
```

#### ACN
```acn
Boolean8 [false-value '00000000'B, true-value '00000001'B]
```

### Additional Context

This issue was identified during the discussions on PROBA3 and reported by Konrad Grochowski from N7 Space.

**Comment by maxime-esa** [comment]
fixed in release https://github.com/maxime-esa/asn1scc/releases/tag/4.5.2.1
