### ISSUE TITLE
ACN headers Not correct

### ISSUE THREAD

**Issue by ErfanBabakhani** [maxime-esa/asn1scc#314]
Hello I use 4.5.2.1 for your calculate_crc test in Doc/example but after running your given command in Command.txt for generating c code I see the asn1crt_encoding_acn.c and asn1crt_encoding_acn.h are not correct 
[asn1crt_encoding_acnC.txt](https://github.com/user-attachments/files/16691252/asn1crt_encoding_acnC.txt)
[asn1crt_encoding_acnHeader.txt](https://github.com/user-attachments/files/16691253/asn1crt_encoding_acnHeader.txt)
I change them to .txt
the first one is  asn1crt_encoding_acn.c
second is asn1crt_encoding_acn.h

you can see their aren't equal as what exist in your Doc/example same files

Regards

**Comment by maxime-esa** [comment]
Indeed, the problem is in the Makefile. At the call of asn1scc it should contain two additional flags:
`-if Acn_Dec_Int_PositiveInteger_ConstSize -if Acn_Enc_Int_PositiveInteger_ConstSize`

You may add them manually in the meantime, the example will build properly afterwards.
